@base_url = http://localhost:3333
@url = {{base_url}}/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4ZjllODVjNS1jOWRkLTQxMzEtYTRlMi1iM2UyMDExNzcwNDYiLCJlbWFpbCI6ImpvaG4uZG9lQGV4YW1wbGUuY29tIiwicHJvZmlsZVR5cGUiOiJRVUVTVCIsImlhdCI6MTc2NTE5ODAyNiwiZXhwIjoxNzY1Mjg0NDI2fQ.eRoI61pF0tUJrNq1-Iel-dgZ-T5h2EyQFxTDorbch-I

###
POST {{url}}/auth/login
Content-Type: application/json

{
  "email": "john.d2oe@example.com",
  "password": "hashed_password"
}

###

GET {{url}}/users
Authorization: Bearer {{token}}

###

POST {{url}}/users HTTP/1.1
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john.doe@example.com",
  "phone": "123-456-7890",
  "birthDate": "1990-01-01",
  "passwordHash": "hashed_password"
}

###

PUT {{url}}/users/434c5fa1-b971-482a-b2b7-b92a21e58044 HTTP/1.1
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john.doe@example.com",
  "phone": "123-456-7890",
  "birthDate": "1990-01-01",
  "passwordHash": "hashed_password"
}

###

DELETE {{url}}/users/434c5fa1-b971-482a-b2b7-b92a21e58044 HTTP/1.1

###

POST {{url}}/address HTTP/1.1
Content-Type: application/json

{
  "cep": "87260000",
  "neighborhood": "lirial de São Luiz",
  "street": "Rodovia Bento Fernandes Dias",
  "number": "R1",
  "complement": "Sítio"
}
