import Footer from "@/components/footer";
import Header from "@/components/header";
import type { Metadata } from "next";
import { Poppins, Roboto } from "next/font/google";
import { Suspense } from "react";
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "600"],
});

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "600"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} ${roboto.className}`}>
        <Header />
        <main>
          <Suspense fallback={<div>Carregando...</div>}>{children}</Suspense>
        </main>
        <Footer />
      </body>
    </html>
  );
}
